# Generated by Django 4.2.17 on 2024-12-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('s_name', models.CharField(max_length=50)),
                ('s_mail', models.EmailField(max_length=254)),
                ('s_contact', models.CharField(max_length=10)),
            ],
        ),
    ]
