# Generated by Django 4.2.17 on 2024-12-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.AlterField(
            model_name='students',
            name='s_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
